// Circuit geometry: anchor points drawn in the editor are the source of truth
// for a track's shape. Smooth SVG paths are generated from them at render
// time, and a compat track.svg can be generated for the asset folder.
//
// All coordinates live in a fixed drawing space (DRAW_WIDTH x DRAW_HEIGHT) so
// every asset shares the same viewBox and the canvas never jumps while
// drawing.

export type TrackGeometryPoint = { x: number; y: number };

export type TrackGeometry = {
  /** Anchor points of the racing line, in draw order. Always a closed loop. */
  racingLine: TrackGeometryPoint[];
  /** Anchor points of the pit lane (open path, in travel direction), or null. */
  pitLane: TrackGeometryPoint[] | null;
  /** Render anchors as smooth Catmull-Rom curves (true) or straight segments. */
  smoothed: boolean;
};

export const DRAW_WIDTH = 1000;
export const DRAW_HEIGHT = 620;
export const DRAW_VIEWBOX = `0 0 ${DRAW_WIDTH} ${DRAW_HEIGHT}`;

export function createEmptyGeometry(): TrackGeometry {
  return { racingLine: [], pitLane: null, smoothed: true };
}

const fmt = (n: number) => Number(n.toFixed(2));

/**
 * Convert anchor points to an SVG path `d` string.
 *
 * Smoothed mode interpolates a centripetal-ish Catmull-Rom spline through the
 * anchors and emits it as cubic beziers: for the segment p1 -> p2 with
 * neighbors p0 and p3, the control points are
 *   c1 = p1 + (p2 - p0) / 6
 *   c2 = p2 - (p3 - p1) / 6
 * which is the standard uniform Catmull-Rom -> bezier conversion. For closed
 * loops the neighbors wrap around; for open paths the end neighbors are
 * clamped (p0 = first, p3 = last), giving natural-looking ends.
 */
export function geometryToPathD(
  points: TrackGeometryPoint[],
  closed: boolean,
  smoothed: boolean,
): string {
  if (points.length === 0) return "";
  if (points.length === 1) return `M ${fmt(points[0].x)} ${fmt(points[0].y)}`;

  if (!smoothed || points.length === 2) {
    const parts = [`M ${fmt(points[0].x)} ${fmt(points[0].y)}`];
    for (let i = 1; i < points.length; i += 1) {
      parts.push(`L ${fmt(points[i].x)} ${fmt(points[i].y)}`);
    }
    if (closed) parts.push("Z");
    return parts.join(" ");
  }

  const n = points.length;
  const at = (i: number) => {
    if (closed) return points[((i % n) + n) % n];
    return points[Math.max(0, Math.min(n - 1, i))];
  };

  const segments = closed ? n : n - 1;
  const parts = [`M ${fmt(points[0].x)} ${fmt(points[0].y)}`];
  for (let i = 0; i < segments; i += 1) {
    const p0 = at(i - 1);
    const p1 = at(i);
    const p2 = at(i + 1);
    const p3 = at(i + 2);
    const c1x = p1.x + (p2.x - p0.x) / 6;
    const c1y = p1.y + (p2.y - p0.y) / 6;
    const c2x = p2.x - (p3.x - p1.x) / 6;
    const c2y = p2.y - (p3.y - p1.y) / 6;
    parts.push(`C ${fmt(c1x)} ${fmt(c1y)}, ${fmt(c2x)} ${fmt(c2y)}, ${fmt(p2.x)} ${fmt(p2.y)}`);
  }
  if (closed) parts.push("Z");
  return parts.join(" ");
}

/**
 * Index of the segment (between anchor i and anchor i+1) nearest to a point.
 * Used to insert a new anchor where the user clicked on the path.
 */
export function nearestSegmentIndex(
  points: TrackGeometryPoint[],
  closed: boolean,
  x: number,
  y: number,
): { index: number; distance: number } | null {
  if (points.length < 2) return null;
  const segments = closed ? points.length : points.length - 1;
  let best: { index: number; distance: number } | null = null;
  for (let i = 0; i < segments; i += 1) {
    const a = points[i];
    const b = points[(i + 1) % points.length];
    // Project the click onto segment a-b, clamped to the segment.
    const abx = b.x - a.x;
    const aby = b.y - a.y;
    const lenSq = abx * abx + aby * aby;
    const t = lenSq === 0 ? 0 : Math.max(0, Math.min(1, ((x - a.x) * abx + (y - a.y) * aby) / lenSq));
    const px = a.x + abx * t;
    const py = a.y + aby * t;
    const distance = Math.hypot(x - px, y - py);
    if (!best || distance < best.distance) best = { index: i, distance };
  }
  return best;
}

/**
 * Generate a standalone track.svg for the asset folder. This file is a
 * compatibility artifact for quick previews outside the app — the game itself
 * renders from the geometry in metadata.json, never from this file.
 */
export function generateTrackSvg(geometry: TrackGeometry): string {
  const racingD = geometryToPathD(geometry.racingLine, true, geometry.smoothed);
  const pitD = geometry.pitLane && geometry.pitLane.length >= 2
    ? geometryToPathD(geometry.pitLane, false, geometry.smoothed)
    : null;

  const lines = [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${DRAW_VIEWBOX}" fill="none">`,
    `  <!-- Generated by the track asset editor from metadata.json geometry. -->`,
    `  <path id="track-asphalt" d="${racingD}" stroke="#39424f" stroke-width="24" stroke-linejoin="round" />`,
    `  <path id="racing-line" d="${racingD}" stroke="#cbd5e1" stroke-width="3" stroke-linejoin="round" />`,
  ];
  if (pitD) {
    lines.push(
      `  <path id="pit-lane" d="${pitD}" stroke="#67e8f9" stroke-width="3" stroke-dasharray="7 5" />`,
    );
  }
  lines.push(`</svg>`, ``);
  return lines.join("\n");
}
